name: string_to_ascii
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
